name = "bevy_easings"
description = "A plugin for easing a component value to another value, mainly used to animate transition between two transforms, but usable for other components."
link = "https://crates.io/crates/bevy_easings"
