name = "autodefault"
description = "annotate functions to have them automatically insert `..Default::default()` into struct expressions. Useful when instantiating large, deeply nested components or component bundles."
link = "https://github.com/Lucretiel/autodefault"
